---
- name: ensure that locale_lang exists
  command: locale-gen "{{ locale_lang }}"

- name: set locale to locale_lang
  command: /usr/sbin/update-locale LANG='{{ locale_lang }}' LC_ALL='{{ locale_lang }}'
  sudo: yes
  notify: reconfigure locales
  when: ansible_os_family == "Debian"

- name: add locale env vars
  lineinfile:
    dest=/etc/bash.bashrc
    line="{{item}}"
    state=present
    insertafter=EOF
    create=True
  with_items:
    - 'export LANGUAGE="{{ locale_lang }}"'
    - 'export LANG="{{ locale_lang }}"'
    - 'export LC_ALL="{{ locale_lang }}"'
  sudo: yes
