---
- hosts: all
  vars_files:
    - app_vars.yml
  vars:
    # shared variables here

  tasks:
    - include: ./tasks/essentials.yml
    - include: ./tasks/customize_shell.yml
    - include: ./tasks/ruby.yml
      vars:
        bundler_version: 1.6.2
    - include: ./tasks/postgresql.yml
    - include: ./tasks/heroku.yml
    - include: ./tasks/app_setup.yml
  handlers:
    - include: ./handlers/postgresql.yml
