---
- hosts: all

  tasks:
    - include: ./tasks/essentials.yml
    - include: ./tasks/customize_shell.yml
    - include: ./tasks/ruby.yml
      vars:
        ruby_version: 2.1.1
#        bundler_version: 1.6.2
    - include: ./tasks/postgresql.yml
      vars:
      # TODO: Make this a variable      
        appname: headache_tracker
    - include: ./tasks/heroku.yml
  handlers:
    - include: ./handlers/postgresql.yml    